# Generated by Django 3.0.2 on 2020-10-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200124_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='userUid',
            field=models.CharField(default='12345678', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='userUid',
            field=models.CharField(default='12345678', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='userUid',
            field=models.CharField(default='12345678', max_length=35),
            preserve_default=False,
        ),
    ]
